name: Release
on: { push: { tags: [ 'v*' ] } }
concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - uses: infrabits/ci-setup-python@main
        with:
          install_dependencies: true
          install_test_dependencies: false
          install_tox: false

      - name: Create release artifact
        run: poetry run ./scripts/create-package.py

      - name: Create GitHub release
        uses: infrabits/ci-create-missing-release@9b9b256bbdf59a093f847f2d7fa18700eaadffa1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          artifacts: drag-and-drop.apkg
